services:
  # ------------------------------------------------
  # Back-end API (NestJS)
  # ------------------------------------------------
  backend:
    container_name: e2ee_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '${API_PORT:-3000}:3000'
    volumes:
      - ./backend:/app
      # Ignora node_modules do host para usar o do container
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
      - storage
    networks:
      - e2ee_network

  # ------------------------------------------------
  # Front-end (React)
  # ------------------------------------------------
  frontend:
    container_name: e2ee_web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-5173}:5173'
    volumes:
      - ./frontend:/app
      # Ignora node_modules do host para usar o do container
      - /app/node_modules
    networks:
      - e2ee_network
    # --- Adicionar esta seção ---
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    # ---------------------------

  # ------------------------------------------------
  # Banco de Dados (PostgreSQL)
  # ------------------------------------------------
  db:
    container_name: e2ee_db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - e2ee_db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432' # Expor apenas para debug local, se necessário
    networks:
      - e2ee_network

  # ------------------------------------------------
  # Armazenamento de Objetos (Minio)
  # ------------------------------------------------
  storage:
    container_name: e2ee_storage
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000' # Porta da API S3
      - '9001:9001' # Porta do Console Web
    volumes:
      - e2ee_storage_data:/data
    networks:
      - e2ee_network

# ------------------------------------------------
# Volumes Persistentes
# ------------------------------------------------
volumes:
  e2ee_db_data:
    driver: local
  e2ee_storage_data:
    driver: local

# ------------------------------------------------
# Rede Privada
# ------------------------------------------------
networks:
  e2ee_network:
    driver: bridge